### ISSUE TITLE
Some translation are missing in french

### ISSUE THREAD

**Issue by vgauther** [hotaydev/dnd-beyond-kit#10]
As you can see, some translation are missing. E.g "chain mail" should be "côte de maille". 

<img width="339" alt="Capture d’écran 2024-12-03 à 19 37 39" src="https://github.com/user-attachments/assets/fbf20bba-b12d-45f0-84ed-867436b6e7f1">

**Comment by TaylorHo** [comment]
Hey @vgauther, thanks for the contribution!

Sadly we don't have all the translations that we would like to have, because we depend on contributions from people worldwide to contribute with translations. The current French translations were made with contributions and part of them were made with AI translations (that could also be revised, nothing is better than a native speaker of the language).

So, if you want to contribute with translations, you're very welcome!

In the [`translations`](https://github.com/hotaydev/dnd-beyond-kit/tree/main/translations) folder we have one JSON file for every translation, with the spell names being separated into a [`translations/spells`](https://github.com/hotaydev/dnd-beyond-kit/tree/main/translations/spells) folder. The French translations are all in the [`fr-fr.json`](https://github.com/hotaydev/dnd-beyond-kit/blob/main/translations/spells/fr-fr.json) files.

The structure to translate anything is the name as is in D&D Beyond in lowercase (example: "chain mail") as the key of the JSON, and the translation in the value of the JSON. Here is a full example of the translation you've mentioned:

```
{
   ... other previous translations ...
    "chain mail": "côte de maille"
}
```

**Comment by TaylorHo** [comment]
We can translate all the strings we currently have using AI-generated translations, and then verify with a native French speaker. If we can do so, it would be amazing to have your help at least with this revision.

What do you think about this?

**Comment by vgauther** [comment]
I'll contribute ;)

**Comment by TaylorHo** [comment]
Your PR was approved and soon the changes will be available in Chrome Web Store and Firefox Add-Ons Store.

You're also very welcome to contribute with more translations in the future 😁
